"""Add decline and unlink fields for Phase 3

Revision ID: 033fd221e8cf
Revises: f1cc30cb20bf
Create Date: 2025-11-19 14:26:25.849797

"""
from typing import Sequence, Union, cast
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '033fd221e8cf'
down_revision: Union[str, None] = 'f1cc30cb20bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('validation_approvals', sa.Column('unlinked_by_id', sa.Integer(), nullable=True))
    op.add_column('validation_approvals', sa.Column('unlink_reason', sa.Text(), nullable=True))
    op.add_column('validation_approvals', sa.Column('unlinked_at', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'validation_approvals', 'users', ['unlinked_by_id'], ['user_id'])
    op.add_column('validation_requests', sa.Column('declined_by_id', sa.Integer(), nullable=True))
    op.add_column('validation_requests', sa.Column('decline_reason', sa.Text(), nullable=True))
    op.add_column('validation_requests', sa.Column('declined_at', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'validation_requests', 'users', ['declined_by_id'], ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(cast(str, None), 'validation_requests', type_='foreignkey')
    op.drop_column('validation_requests', 'declined_at')
    op.drop_column('validation_requests', 'decline_reason')
    op.drop_column('validation_requests', 'declined_by_id')
    op.drop_constraint(cast(str, None), 'validation_approvals', type_='foreignkey')
    op.drop_column('validation_approvals', 'unlinked_at')
    op.drop_column('validation_approvals', 'unlink_reason')
    op.drop_column('validation_approvals', 'unlinked_by_id')
    # ### end Alembic commands ###
