"""add_multi_model_support_to_validation_requests

Revision ID: 13f967c5714a
Revises: 1bbfd0b0ef09
Create Date: 2025-11-19 07:46:09.513197

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13f967c5714a'
down_revision: Union[str, None] = '1bbfd0b0ef09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Step 1: Create the new association table
    op.create_table('validation_request_models',
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['models.model_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['request_id'], ['validation_requests.request_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('request_id', 'model_id')
    )

    # Step 2: Migrate existing data from validation_requests.model_id to the association table
    connection = op.get_bind()
    connection.execute(sa.text("""
        INSERT INTO validation_request_models (request_id, model_id)
        SELECT request_id, model_id
        FROM validation_requests
        WHERE model_id IS NOT NULL
    """))

    # Step 3: Drop the old foreign key and column
    op.drop_constraint('validation_requests_model_id_fkey', 'validation_requests', type_='foreignkey')
    op.drop_column('validation_requests', 'model_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('validation_requests', sa.Column('model_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('validation_requests_model_id_fkey', 'validation_requests', 'models', ['model_id'], ['model_id'], ondelete='CASCADE')
    op.drop_table('validation_request_models')
    # ### end Alembic commands ###
