"""add regional_risk_level to model_regions

Revision ID: 1bbfd0b0ef09
Revises: caba5b47fe3b
Create Date: 2025-11-19 07:18:52.267040

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1bbfd0b0ef09'
down_revision: Union[str, None] = 'caba5b47fe3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('model_regions', sa.Column('regional_risk_level', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('model_regions', 'regional_risk_level')
    # ### end Alembic commands ###
