"""Add export views table

Revision ID: 1d5535a827bf
Revises: bb4e0262b97a
Create Date: 2025-11-21 18:12:48.323476

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d5535a827bf'
down_revision: Union[str, None] = 'bb4e0262b97a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('export_views',
    sa.Column('view_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False, comment="Entity type (e.g., 'models', 'validations')"),
    sa.Column('view_name', sa.String(length=100), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False, comment='If true, all users can see this view'),
    sa.Column('columns', sa.JSON(), nullable=False, comment='Array of column keys to include in export'),
    sa.Column('description', sa.Text(), nullable=True, comment='Optional description of what this view is for'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('view_id')
    )
    op.drop_index('ix_model_submission_comments_model_id', table_name='model_submission_comments')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_model_submission_comments_model_id', 'model_submission_comments', ['model_id'], unique=False)
    op.drop_table('export_views')
    # ### end Alembic commands ###
