"""Add regional scope and deployment tracking to model versions

Revision ID: 2f2022f1346b
Revises: 1d5535a827bf
Create Date: 2025-11-21 18:34:57.804971

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f2022f1346b'
down_revision: Union[str, None] = '1d5535a827bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('model_regions', sa.Column('deployed_at', sa.DateTime(), nullable=True, comment='When this version was deployed to this region'))
    op.add_column('model_regions', sa.Column('deployment_notes', sa.Text(), nullable=True, comment='Notes about this regional deployment'))
    op.alter_column('model_regions', 'version_id',
               existing_type=sa.INTEGER(),
               comment='Current active version deployed in this region',
               existing_nullable=True)

    # Add scope column in two steps to handle existing data
    # Step 1: Add as nullable with default
    op.add_column('model_versions', sa.Column('scope', sa.String(length=20), nullable=True, server_default='GLOBAL'))
    # Step 2: Update any NULL values to 'GLOBAL'
    op.execute("UPDATE model_versions SET scope = 'GLOBAL' WHERE scope IS NULL")
    # Step 3: Make it NOT NULL
    op.alter_column('model_versions', 'scope', nullable=False)

    op.add_column('model_versions', sa.Column('affected_region_ids', sa.JSON(), nullable=True, comment='List of region IDs affected by this change (for REGIONAL scope)'))
    op.add_column('model_versions', sa.Column('planned_production_date', sa.Date(), nullable=True, comment='Planned/target production date'))
    op.add_column('model_versions', sa.Column('actual_production_date', sa.Date(), nullable=True, comment='Actual date when deployed to production'))

    # Copy existing production_date to planned_production_date for existing records
    op.execute("UPDATE model_versions SET planned_production_date = production_date WHERE production_date IS NOT NULL")

    op.alter_column('model_versions', 'production_date',
               existing_type=sa.DATE(),
               comment='Legacy field - maps to planned_production_date',
               existing_nullable=True)
    op.create_index(op.f('ix_model_versions_scope'), 'model_versions', ['scope'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_model_versions_scope'), table_name='model_versions')
    op.alter_column('model_versions', 'production_date',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='Legacy field - maps to planned_production_date',
               existing_nullable=True)
    op.drop_column('model_versions', 'actual_production_date')
    op.drop_column('model_versions', 'planned_production_date')
    op.drop_column('model_versions', 'affected_region_ids')
    op.drop_column('model_versions', 'scope')
    op.alter_column('model_regions', 'version_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Current active version deployed in this region',
               existing_nullable=True)
    op.drop_column('model_regions', 'deployment_notes')
    op.drop_column('model_regions', 'deployed_at')
    # ### end Alembic commands ###
