"""Add component definition versioning and plan locking

Revision ID: 373700cdc73d
Revises: cc568f455fb3
Create Date: 2025-11-22 16:06:44.964548

"""
from typing import Sequence, Union, cast
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '373700cdc73d'
down_revision: Union[str, None] = 'cc568f455fb3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('component_definition_configurations',
    sa.Column('config_id', sa.Integer(), nullable=False),
    sa.Column('config_name', sa.String(length=200), nullable=False, comment="e.g., '2025-11-22 Initial Configuration', 'Q2 2026 SR 11-7 Update'"),
    sa.Column('description', sa.Text(), nullable=True, comment='Details about this configuration version'),
    sa.Column('effective_date', sa.Date(), nullable=False, comment='When this configuration took effect'),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Only one configuration is active at a time'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.user_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('config_id')
    )
    op.create_table('component_definition_config_items',
    sa.Column('config_item_id', sa.Integer(), nullable=False),
    sa.Column('config_id', sa.Integer(), nullable=False),
    sa.Column('component_id', sa.Integer(), nullable=False),
    sa.Column('expectation_high', sa.String(length=20), nullable=False),
    sa.Column('expectation_medium', sa.String(length=20), nullable=False),
    sa.Column('expectation_low', sa.String(length=20), nullable=False),
    sa.Column('expectation_very_low', sa.String(length=20), nullable=False),
    sa.Column('section_number', sa.String(length=10), nullable=False),
    sa.Column('section_title', sa.String(length=200), nullable=False),
    sa.Column('component_code', sa.String(length=20), nullable=False),
    sa.Column('component_title', sa.String(length=200), nullable=False),
    sa.Column('is_test_or_analysis', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['component_id'], ['validation_component_definitions.component_id'], ),
    sa.ForeignKeyConstraint(['config_id'], ['component_definition_configurations.config_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('config_item_id')
    )
    op.add_column('validation_plans', sa.Column('config_id', sa.Integer(), nullable=True, comment='Configuration version this plan is linked to (locked when plan submitted for review)'))
    op.add_column('validation_plans', sa.Column('locked_at', sa.DateTime(), nullable=True, comment='When plan was locked (moved to Review/Pending Approval)'))
    op.add_column('validation_plans', sa.Column('locked_by_user_id', sa.Integer(), nullable=True, comment='User who triggered the lock (via status transition)'))
    op.create_foreign_key(None, 'validation_plans', 'component_definition_configurations', ['config_id'], ['config_id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'validation_plans', 'users', ['locked_by_user_id'], ['user_id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(cast(str, None), 'validation_plans', type_='foreignkey')
    op.drop_constraint(cast(str, None), 'validation_plans', type_='foreignkey')
    op.drop_column('validation_plans', 'locked_by_user_id')
    op.drop_column('validation_plans', 'locked_at')
    op.drop_column('validation_plans', 'config_id')
    op.drop_table('component_definition_config_items')
    op.drop_table('component_definition_configurations')
    # ### end Alembic commands ###
