"""add_recommendations_tables

Revision ID: 3d0a564c4fe3
Revises: f36f4f06ec65
Create Date: 2025-11-30 13:10:28.779189

"""
from typing import Sequence, Union, cast
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d0a564c4fe3'
down_revision: Union[str, None] = 'f36f4f06ec65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recommendation_priority_configs',
    sa.Column('config_id', sa.Integer(), nullable=False),
    sa.Column('priority_id', sa.Integer(), nullable=False, comment='FK to priority taxonomy value (High/Medium/Low)'),
    sa.Column('requires_final_approval', sa.Boolean(), nullable=False, comment='If true, closure requires Global + Regional approvals after Validator approval'),
    sa.Column('description', sa.Text(), nullable=True, comment='Admin notes explaining the configuration'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['priority_id'], ['taxonomy_values.value_id'], ),
    sa.PrimaryKeyConstraint('config_id'),
    sa.UniqueConstraint('priority_id')
    )
    op.create_table('recommendations',
    sa.Column('recommendation_id', sa.Integer(), nullable=False),
    sa.Column('recommendation_code', sa.String(length=20), nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.Column('validation_request_id', sa.Integer(), nullable=True, comment='Link to originating validation (if applicable)'),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('root_cause_analysis', sa.Text(), nullable=True),
    sa.Column('priority_id', sa.Integer(), nullable=False, comment='High/Medium/Low - determines closure approval requirements'),
    sa.Column('category_id', sa.Integer(), nullable=True, comment='e.g., Data Quality, Methodology, Implementation, Documentation'),
    sa.Column('current_status_id', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=False, comment='Validator who identified the issue'),
    sa.Column('assigned_to_id', sa.Integer(), nullable=False, comment='Developer/Owner responsible for remediation'),
    sa.Column('original_target_date', sa.Date(), nullable=False),
    sa.Column('current_target_date', sa.Date(), nullable=False),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('closed_by_id', sa.Integer(), nullable=True),
    sa.Column('closure_summary', sa.Text(), nullable=True),
    sa.Column('finalized_at', sa.DateTime(), nullable=True),
    sa.Column('finalized_by_id', sa.Integer(), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(), nullable=True),
    sa.Column('acknowledged_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['acknowledged_by_id'], ['users.user_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['taxonomy_values.value_id'], ),
    sa.ForeignKeyConstraint(['closed_by_id'], ['users.user_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['current_status_id'], ['taxonomy_values.value_id'], ),
    sa.ForeignKeyConstraint(['finalized_by_id'], ['users.user_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['model_id'], ['models.model_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['priority_id'], ['taxonomy_values.value_id'], ),
    sa.ForeignKeyConstraint(['validation_request_id'], ['validation_requests.request_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('recommendation_id')
    )
    op.create_index(op.f('ix_recommendations_model_id'), 'recommendations', ['model_id'], unique=False)
    op.create_index(op.f('ix_recommendations_recommendation_code'), 'recommendations', ['recommendation_code'], unique=True)
    op.create_index(op.f('ix_recommendations_validation_request_id'), 'recommendations', ['validation_request_id'], unique=False)
    op.create_table('action_plan_tasks',
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('recommendation_id', sa.Integer(), nullable=False),
    sa.Column('task_order', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=False),
    sa.Column('completed_date', sa.Date(), nullable=True),
    sa.Column('completion_status_id', sa.Integer(), nullable=False, comment='NOT_STARTED, IN_PROGRESS, COMPLETED'),
    sa.Column('completion_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['completion_status_id'], ['taxonomy_values.value_id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['recommendation_id'], ['recommendations.recommendation_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('task_id'),
    sa.UniqueConstraint('recommendation_id', 'task_order', name='uq_rec_task_order')
    )
    op.create_index(op.f('ix_action_plan_tasks_recommendation_id'), 'action_plan_tasks', ['recommendation_id'], unique=False)
    op.create_table('closure_evidence',
    sa.Column('evidence_id', sa.Integer(), nullable=False),
    sa.Column('recommendation_id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False, comment='Storage path or URL to evidence document'),
    sa.Column('file_type', sa.String(length=50), nullable=True),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('uploaded_by_id', sa.Integer(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['recommendation_id'], ['recommendations.recommendation_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('evidence_id')
    )
    op.create_index(op.f('ix_closure_evidence_recommendation_id'), 'closure_evidence', ['recommendation_id'], unique=False)
    op.create_table('recommendation_approvals',
    sa.Column('approval_id', sa.Integer(), nullable=False),
    sa.Column('recommendation_id', sa.Integer(), nullable=False),
    sa.Column('approval_type', sa.String(length=20), nullable=False, comment="'GLOBAL' or 'REGIONAL'"),
    sa.Column('region_id', sa.Integer(), nullable=True, comment="Required if approval_type='REGIONAL', NULL for GLOBAL"),
    sa.Column('represented_region_id', sa.Integer(), nullable=True, comment='Region the approver was representing at approval time (NULL for Global Approver)'),
    sa.Column('approver_id', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('approval_status', sa.String(length=20), nullable=False, comment='PENDING, APPROVED, REJECTED, VOIDED'),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('approval_evidence', sa.Text(), nullable=True, comment='Description of approval evidence (meeting minutes, email, etc.) - required for Admin proxy approvals'),
    sa.Column('voided_by_id', sa.Integer(), nullable=True),
    sa.Column('void_reason', sa.Text(), nullable=True),
    sa.Column('voided_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("approval_status IN ('PENDING', 'APPROVED', 'REJECTED', 'VOIDED')", name='chk_rec_approval_status'),
    sa.CheckConstraint("approval_type IN ('GLOBAL', 'REGIONAL')", name='chk_rec_approval_type'),
    sa.ForeignKeyConstraint(['approver_id'], ['users.user_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['recommendation_id'], ['recommendations.recommendation_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['region_id'], ['regions.region_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['represented_region_id'], ['regions.region_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['voided_by_id'], ['users.user_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('approval_id'),
    sa.UniqueConstraint('recommendation_id', 'approval_type', 'region_id', name='uq_rec_approval_type_region')
    )
    op.create_index(op.f('ix_recommendation_approvals_recommendation_id'), 'recommendation_approvals', ['recommendation_id'], unique=False)
    op.create_index(op.f('ix_recommendation_approvals_represented_region_id'), 'recommendation_approvals', ['represented_region_id'], unique=False)
    op.create_table('recommendation_rebuttals',
    sa.Column('rebuttal_id', sa.Integer(), nullable=False),
    sa.Column('recommendation_id', sa.Integer(), nullable=False),
    sa.Column('submitted_by_id', sa.Integer(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('supporting_evidence', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=False),
    sa.Column('reviewed_by_id', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('review_decision', sa.String(length=20), nullable=True, comment='ACCEPT (issue dropped) or OVERRIDE (action plan required)'),
    sa.Column('review_comments', sa.Text(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.CheckConstraint("review_decision IN ('ACCEPT', 'OVERRIDE') OR review_decision IS NULL", name='chk_rebuttal_decision'),
    sa.ForeignKeyConstraint(['recommendation_id'], ['recommendations.recommendation_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['users.user_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['submitted_by_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('rebuttal_id')
    )
    op.create_index(op.f('ix_recommendation_rebuttals_recommendation_id'), 'recommendation_rebuttals', ['recommendation_id'], unique=False)
    op.create_table('recommendation_status_history',
    sa.Column('history_id', sa.Integer(), nullable=False),
    sa.Column('recommendation_id', sa.Integer(), nullable=False),
    sa.Column('old_status_id', sa.Integer(), nullable=True),
    sa.Column('new_status_id', sa.Integer(), nullable=False),
    sa.Column('changed_by_id', sa.Integer(), nullable=False),
    sa.Column('changed_at', sa.DateTime(), nullable=False),
    sa.Column('change_reason', sa.Text(), nullable=True),
    sa.Column('additional_context', sa.Text(), nullable=True, comment='JSON storing action-specific details'),
    sa.ForeignKeyConstraint(['changed_by_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['new_status_id'], ['taxonomy_values.value_id'], ),
    sa.ForeignKeyConstraint(['old_status_id'], ['taxonomy_values.value_id'], ),
    sa.ForeignKeyConstraint(['recommendation_id'], ['recommendations.recommendation_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('history_id')
    )
    op.create_index(op.f('ix_recommendation_status_history_recommendation_id'), 'recommendation_status_history', ['recommendation_id'], unique=False)
    op.drop_index('ix_decom_approvals_pending', table_name='decommissioning_approvals')
    op.drop_index('ix_decom_requests_status', table_name='decommissioning_requests')
    op.alter_column('map_applications', 'description',
               existing_type=sa.TEXT(),
               comment="Description of the application's purpose",
               existing_comment='Description of the application purpose',
               existing_nullable=True)
    op.alter_column('map_applications', 'technology_stack',
               existing_type=sa.VARCHAR(length=255),
               comment='Technology stack (e.g., Python/AWS Lambda, Java/On-Prem)',
               existing_comment='Technology stack (e.g., Python/AWS Lambda)',
               existing_nullable=True)
    op.alter_column('map_applications', 'external_url',
               existing_type=sa.VARCHAR(length=500),
               comment='Link to MAP system record for this application',
               existing_comment='Link to MAP system record',
               existing_nullable=True)
    op.drop_index('ix_map_applications_department', table_name='map_applications')
    op.drop_index('ix_map_applications_status', table_name='map_applications')
    op.drop_index('ix_model_applications_application_id', table_name='model_applications')
    op.drop_index('ix_model_pending_edits_model_id', table_name='model_pending_edits')
    op.drop_index('ix_model_pending_edits_status', table_name='model_pending_edits')
    op.drop_index('idx_monitoring_cycle_approvals_cycle', table_name='monitoring_cycle_approvals')
    op.drop_index('idx_monitoring_cycle_approvals_status', table_name='monitoring_cycle_approvals')
    op.drop_constraint('unique_cycle_approval', 'monitoring_cycle_approvals', type_='unique')
    op.create_index(op.f('ix_monitoring_cycle_approvals_cycle_id'), 'monitoring_cycle_approvals', ['cycle_id'], unique=False)
    op.drop_index('idx_mc_plan_version_id', table_name='monitoring_cycles')
    op.drop_index('idx_monitoring_cycles_plan_id', table_name='monitoring_cycles')
    op.drop_index('idx_monitoring_cycles_status', table_name='monitoring_cycles')
    op.create_index(op.f('ix_monitoring_cycles_plan_id'), 'monitoring_cycles', ['plan_id'], unique=False)
    op.create_index(op.f('ix_monitoring_cycles_plan_version_id'), 'monitoring_cycles', ['plan_version_id'], unique=False)
    op.drop_index('idx_mpms_version_id', table_name='monitoring_plan_metric_snapshots')
    op.create_index(op.f('ix_monitoring_plan_metric_snapshots_version_id'), 'monitoring_plan_metric_snapshots', ['version_id'], unique=False)
    op.alter_column('monitoring_plan_metrics', 'yellow_min',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Minimum value for yellow/warning status',
               existing_nullable=True)
    op.alter_column('monitoring_plan_metrics', 'yellow_max',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Maximum value for yellow/warning status',
               existing_nullable=True)
    op.alter_column('monitoring_plan_metrics', 'red_min',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Minimum value for red/critical status',
               existing_nullable=True)
    op.alter_column('monitoring_plan_metrics', 'red_max',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Maximum value for red/critical status',
               existing_nullable=True)
    op.alter_column('monitoring_plan_metrics', 'qualitative_guidance',
               existing_type=sa.TEXT(),
               comment='Qualitative guidance for interpreting this metric in the plan context',
               existing_nullable=True)
    op.drop_index('idx_mpv_is_active', table_name='monitoring_plan_versions')
    op.drop_index('idx_mpv_plan_id', table_name='monitoring_plan_versions')
    op.create_index(op.f('ix_monitoring_plan_versions_plan_id'), 'monitoring_plan_versions', ['plan_id'], unique=False)
    op.alter_column('monitoring_plans', 'reporting_lead_days',
               existing_type=sa.INTEGER(),
               comment='Days between data submission due date and report due date',
               existing_nullable=False,
               existing_server_default=sa.text('30'))
    op.alter_column('monitoring_plans', 'next_submission_due_date',
               existing_type=sa.DATE(),
               comment='Next due date for data submission',
               existing_nullable=True)
    op.alter_column('monitoring_plans', 'next_report_due_date',
               existing_type=sa.DATE(),
               comment='Next due date for monitoring report',
               existing_nullable=True)
    op.drop_index('idx_monitoring_results_cycle', table_name='monitoring_results')
    op.drop_index('idx_monitoring_results_metric', table_name='monitoring_results')
    op.drop_index('idx_monitoring_results_model', table_name='monitoring_results')
    op.drop_index('idx_monitoring_results_outcome', table_name='monitoring_results')
    op.drop_constraint('unique_result', 'monitoring_results', type_='unique')
    op.create_index(op.f('ix_monitoring_results_calculated_outcome'), 'monitoring_results', ['calculated_outcome'], unique=False)
    op.create_index(op.f('ix_monitoring_results_cycle_id'), 'monitoring_results', ['cycle_id'], unique=False)
    op.create_index(op.f('ix_monitoring_results_model_id'), 'monitoring_results', ['model_id'], unique=False)
    op.create_index(op.f('ix_monitoring_results_plan_metric_id'), 'monitoring_results', ['plan_metric_id'], unique=False)
    op.drop_constraint('monitoring_results_entered_by_user_id_fkey', 'monitoring_results', type_='foreignkey')
    op.create_foreign_key(None, 'monitoring_results', 'users', ['entered_by_user_id'], ['user_id'])
    op.drop_index('ix_overdue_comments_created_by', table_name='overdue_revalidation_comments')
    op.drop_index('ix_overdue_comments_request_current', table_name='overdue_revalidation_comments')
    op.create_index(op.f('ix_overdue_revalidation_comments_is_current'), 'overdue_revalidation_comments', ['is_current'], unique=False)
    op.create_index(op.f('ix_overdue_revalidation_comments_validation_request_id'), 'overdue_revalidation_comments', ['validation_request_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_overdue_revalidation_comments_validation_request_id'), table_name='overdue_revalidation_comments')
    op.drop_index(op.f('ix_overdue_revalidation_comments_is_current'), table_name='overdue_revalidation_comments')
    op.create_index('ix_overdue_comments_request_current', 'overdue_revalidation_comments', ['validation_request_id', 'is_current'], unique=False)
    op.create_index('ix_overdue_comments_created_by', 'overdue_revalidation_comments', ['created_by_user_id'], unique=False)
    op.drop_constraint(cast(str, None), 'monitoring_results', type_='foreignkey')
    op.create_foreign_key('monitoring_results_entered_by_user_id_fkey', 'monitoring_results', 'users', ['entered_by_user_id'], ['user_id'], ondelete='RESTRICT')
    op.drop_index(op.f('ix_monitoring_results_plan_metric_id'), table_name='monitoring_results')
    op.drop_index(op.f('ix_monitoring_results_model_id'), table_name='monitoring_results')
    op.drop_index(op.f('ix_monitoring_results_cycle_id'), table_name='monitoring_results')
    op.drop_index(op.f('ix_monitoring_results_calculated_outcome'), table_name='monitoring_results')
    op.create_unique_constraint('unique_result', 'monitoring_results', ['cycle_id', 'plan_metric_id', 'model_id'])
    op.create_index('idx_monitoring_results_outcome', 'monitoring_results', ['calculated_outcome'], unique=False)
    op.create_index('idx_monitoring_results_model', 'monitoring_results', ['model_id'], unique=False)
    op.create_index('idx_monitoring_results_metric', 'monitoring_results', ['plan_metric_id'], unique=False)
    op.create_index('idx_monitoring_results_cycle', 'monitoring_results', ['cycle_id'], unique=False)
    op.alter_column('monitoring_plans', 'next_report_due_date',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='Next due date for monitoring report',
               existing_nullable=True)
    op.alter_column('monitoring_plans', 'next_submission_due_date',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='Next due date for data submission',
               existing_nullable=True)
    op.alter_column('monitoring_plans', 'reporting_lead_days',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Days between data submission due date and report due date',
               existing_nullable=False,
               existing_server_default=sa.text('30'))
    op.drop_index(op.f('ix_monitoring_plan_versions_plan_id'), table_name='monitoring_plan_versions')
    op.create_index('idx_mpv_plan_id', 'monitoring_plan_versions', ['plan_id'], unique=False)
    op.create_index('idx_mpv_is_active', 'monitoring_plan_versions', ['is_active'], unique=False)
    op.alter_column('monitoring_plan_metrics', 'qualitative_guidance',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Qualitative guidance for interpreting this metric in the plan context',
               existing_nullable=True)
    op.alter_column('monitoring_plan_metrics', 'red_max',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Maximum value for red/critical status',
               existing_nullable=True)
    op.alter_column('monitoring_plan_metrics', 'red_min',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Minimum value for red/critical status',
               existing_nullable=True)
    op.alter_column('monitoring_plan_metrics', 'yellow_max',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Maximum value for yellow/warning status',
               existing_nullable=True)
    op.alter_column('monitoring_plan_metrics', 'yellow_min',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Minimum value for yellow/warning status',
               existing_nullable=True)
    op.drop_index(op.f('ix_monitoring_plan_metric_snapshots_version_id'), table_name='monitoring_plan_metric_snapshots')
    op.create_index('idx_mpms_version_id', 'monitoring_plan_metric_snapshots', ['version_id'], unique=False)
    op.drop_index(op.f('ix_monitoring_cycles_plan_version_id'), table_name='monitoring_cycles')
    op.drop_index(op.f('ix_monitoring_cycles_plan_id'), table_name='monitoring_cycles')
    op.create_index('idx_monitoring_cycles_status', 'monitoring_cycles', ['status'], unique=False)
    op.create_index('idx_monitoring_cycles_plan_id', 'monitoring_cycles', ['plan_id'], unique=False)
    op.create_index('idx_mc_plan_version_id', 'monitoring_cycles', ['plan_version_id'], unique=False)
    op.drop_index(op.f('ix_monitoring_cycle_approvals_cycle_id'), table_name='monitoring_cycle_approvals')
    op.create_unique_constraint('unique_cycle_approval', 'monitoring_cycle_approvals', ['cycle_id', 'approval_type', 'region_id'])
    op.create_index('idx_monitoring_cycle_approvals_status', 'monitoring_cycle_approvals', ['approval_status'], unique=False)
    op.create_index('idx_monitoring_cycle_approvals_cycle', 'monitoring_cycle_approvals', ['cycle_id'], unique=False)
    op.create_index('ix_model_pending_edits_status', 'model_pending_edits', ['status'], unique=False)
    op.create_index('ix_model_pending_edits_model_id', 'model_pending_edits', ['model_id'], unique=False)
    op.create_index('ix_model_applications_application_id', 'model_applications', ['application_id'], unique=False)
    op.create_index('ix_map_applications_status', 'map_applications', ['status'], unique=False)
    op.create_index('ix_map_applications_department', 'map_applications', ['department'], unique=False)
    op.alter_column('map_applications', 'external_url',
               existing_type=sa.VARCHAR(length=500),
               comment='Link to MAP system record',
               existing_comment='Link to MAP system record for this application',
               existing_nullable=True)
    op.alter_column('map_applications', 'technology_stack',
               existing_type=sa.VARCHAR(length=255),
               comment='Technology stack (e.g., Python/AWS Lambda)',
               existing_comment='Technology stack (e.g., Python/AWS Lambda, Java/On-Prem)',
               existing_nullable=True)
    op.alter_column('map_applications', 'description',
               existing_type=sa.TEXT(),
               comment='Description of the application purpose',
               existing_comment="Description of the application's purpose",
               existing_nullable=True)
    op.create_index('ix_decom_requests_status', 'decommissioning_requests', ['status'], unique=False)
    op.create_index('ix_decom_approvals_pending', 'decommissioning_approvals', ['request_id', 'is_approved'], unique=False)
    op.drop_index(op.f('ix_recommendation_status_history_recommendation_id'), table_name='recommendation_status_history')
    op.drop_table('recommendation_status_history')
    op.drop_index(op.f('ix_recommendation_rebuttals_recommendation_id'), table_name='recommendation_rebuttals')
    op.drop_table('recommendation_rebuttals')
    op.drop_index(op.f('ix_recommendation_approvals_represented_region_id'), table_name='recommendation_approvals')
    op.drop_index(op.f('ix_recommendation_approvals_recommendation_id'), table_name='recommendation_approvals')
    op.drop_table('recommendation_approvals')
    op.drop_index(op.f('ix_closure_evidence_recommendation_id'), table_name='closure_evidence')
    op.drop_table('closure_evidence')
    op.drop_index(op.f('ix_action_plan_tasks_recommendation_id'), table_name='action_plan_tasks')
    op.drop_table('action_plan_tasks')
    op.drop_index(op.f('ix_recommendations_validation_request_id'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_recommendation_code'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_model_id'), table_name='recommendations')
    op.drop_table('recommendations')
    op.drop_table('recommendation_priority_configs')
    # ### end Alembic commands ###
