"""Add model hierarchy and dependency tables

Revision ID: 3d1d60cd95d2
Revises: 4b1d659c419b
Create Date: 2025-11-23 17:24:03.367106

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d1d60cd95d2'
down_revision: Union[str, None] = '4b1d659c419b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_feed_dependencies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('feeder_model_id', sa.Integer(), nullable=False),
    sa.Column('consumer_model_id', sa.Integer(), nullable=False),
    sa.Column('dependency_type_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.CheckConstraint('end_date IS NULL OR effective_date IS NULL OR end_date >= effective_date', name='ck_dependency_date_range'),
    sa.CheckConstraint('feeder_model_id != consumer_model_id', name='ck_dependency_no_self_ref'),
    sa.ForeignKeyConstraint(['consumer_model_id'], ['models.model_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['dependency_type_id'], ['taxonomy_values.value_id'], ),
    sa.ForeignKeyConstraint(['feeder_model_id'], ['models.model_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('feeder_model_id', 'consumer_model_id', 'dependency_type_id', name='uq_model_dependency')
    )
    op.create_index(op.f('ix_model_feed_dependencies_consumer_model_id'), 'model_feed_dependencies', ['consumer_model_id'], unique=False)
    op.create_index(op.f('ix_model_feed_dependencies_feeder_model_id'), 'model_feed_dependencies', ['feeder_model_id'], unique=False)
    op.create_table('model_hierarchy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_model_id', sa.Integer(), nullable=False),
    sa.Column('child_model_id', sa.Integer(), nullable=False),
    sa.Column('relation_type_id', sa.Integer(), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.CheckConstraint('end_date IS NULL OR effective_date IS NULL OR end_date >= effective_date', name='ck_hierarchy_date_range'),
    sa.CheckConstraint('parent_model_id != child_model_id', name='ck_hierarchy_no_self_ref'),
    sa.ForeignKeyConstraint(['child_model_id'], ['models.model_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_model_id'], ['models.model_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['relation_type_id'], ['taxonomy_values.value_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('parent_model_id', 'child_model_id', 'relation_type_id', 'effective_date', name='uq_model_hierarchy')
    )
    op.create_index(op.f('ix_model_hierarchy_child_model_id'), 'model_hierarchy', ['child_model_id'], unique=False)
    op.create_index(op.f('ix_model_hierarchy_parent_model_id'), 'model_hierarchy', ['parent_model_id'], unique=False)
    op.create_table('model_dependency_metadata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dependency_id', sa.Integer(), nullable=False),
    sa.Column('feed_frequency_id', sa.Integer(), nullable=True),
    sa.Column('interface_type_id', sa.Integer(), nullable=True),
    sa.Column('criticality_id', sa.Integer(), nullable=True),
    sa.Column('data_fields_summary', sa.Text(), nullable=True),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.Column('data_contract_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['criticality_id'], ['taxonomy_values.value_id'], ),
    sa.ForeignKeyConstraint(['dependency_id'], ['model_feed_dependencies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['feed_frequency_id'], ['taxonomy_values.value_id'], ),
    sa.ForeignKeyConstraint(['interface_type_id'], ['taxonomy_values.value_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_dependency_metadata_dependency_id'), 'model_dependency_metadata', ['dependency_id'], unique=True)
    op.alter_column('model_versions', 'production_date',
               existing_type=sa.DATE(),
               comment='Legacy field - prefer planned/actual; maps to planned_production_date',
               existing_comment='Legacy field - maps to planned_production_date',
               existing_nullable=True)
    op.alter_column('regions', 'enforce_validation_plan',
               existing_type=sa.BOOLEAN(),
               comment='When true, validation plans are required for requests scoped to this region',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('regions', 'enforce_validation_plan',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='When true, validation plans are required for requests scoped to this region',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('model_versions', 'production_date',
               existing_type=sa.DATE(),
               comment='Legacy field - maps to planned_production_date',
               existing_comment='Legacy field - prefer planned/actual; maps to planned_production_date',
               existing_nullable=True)
    op.drop_index(op.f('ix_model_dependency_metadata_dependency_id'), table_name='model_dependency_metadata')
    op.drop_table('model_dependency_metadata')
    op.drop_index(op.f('ix_model_hierarchy_parent_model_id'), table_name='model_hierarchy')
    op.drop_index(op.f('ix_model_hierarchy_child_model_id'), table_name='model_hierarchy')
    op.drop_table('model_hierarchy')
    op.drop_index(op.f('ix_model_feed_dependencies_feeder_model_id'), table_name='model_feed_dependencies')
    op.drop_index(op.f('ix_model_feed_dependencies_consumer_model_id'), table_name='model_feed_dependencies')
    op.drop_table('model_feed_dependencies')
    # ### end Alembic commands ###
