"""add_saved_queries_table

Revision ID: 42617ec50a54
Revises: bd848d041e15
Create Date: 2025-11-22 03:57:49.596995

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '42617ec50a54'
down_revision: Union[str, None] = 'bd848d041e15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_version_deployment_tasks_assigned_to_id', table_name='version_deployment_tasks')
    op.drop_index('ix_version_deployment_tasks_planned_date', table_name='version_deployment_tasks')
    op.drop_index('ix_version_deployment_tasks_status', table_name='version_deployment_tasks')
    op.drop_table('version_deployment_tasks')
    op.drop_index('idx_validation_approvals_region', table_name='validation_approvals', postgresql_where='(region_id IS NOT NULL)')
    op.alter_column('validation_requests', 'completion_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Date when validation was completed (latest approval date)',
               existing_nullable=True)
    op.drop_index('idx_validation_requests_completion_date', table_name='validation_requests')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_validation_requests_completion_date', 'validation_requests', ['completion_date'], unique=False)
    op.alter_column('validation_requests', 'completion_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Date when validation was completed (latest approval date)',
               existing_nullable=True)
    op.create_index('idx_validation_approvals_region', 'validation_approvals', ['region_id'], unique=False, postgresql_where='(region_id IS NOT NULL)')
    op.create_table('version_deployment_tasks',
    sa.Column('task_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('version_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('model_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('region_id', sa.INTEGER(), autoincrement=False, nullable=True, comment='NULL for global deployment'),
    sa.Column('planned_production_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('actual_production_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('assigned_to_id', sa.INTEGER(), autoincrement=False, nullable=False, comment='Model Owner or delegate'),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'PENDING'::character varying"), autoincrement=False, nullable=False),
    sa.Column('confirmation_notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('confirmed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('confirmed_by_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('deployed_before_validation_approved', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False, comment='True if deployed before validation was approved'),
    sa.Column('validation_override_reason', sa.TEXT(), autoincrement=False, nullable=True, comment='Justification for deploying before validation approval'),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['users.user_id'], name='version_deployment_tasks_assigned_to_id_fkey'),
    sa.ForeignKeyConstraint(['confirmed_by_id'], ['users.user_id'], name='version_deployment_tasks_confirmed_by_id_fkey'),
    sa.ForeignKeyConstraint(['model_id'], ['models.model_id'], name='version_deployment_tasks_model_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['region_id'], ['regions.region_id'], name='version_deployment_tasks_region_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['version_id'], ['model_versions.version_id'], name='version_deployment_tasks_version_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('task_id', name='version_deployment_tasks_pkey')
    )
    op.create_index('ix_version_deployment_tasks_status', 'version_deployment_tasks', ['status'], unique=False)
    op.create_index('ix_version_deployment_tasks_planned_date', 'version_deployment_tasks', ['planned_production_date'], unique=False)
    op.create_index('ix_version_deployment_tasks_assigned_to_id', 'version_deployment_tasks', ['assigned_to_id'], unique=False)
    # ### end Alembic commands ###
