"""add_model_delegates_table

Revision ID: 4319c7486942
Revises: 9d85f82c5e03
Create Date: 2025-11-18 02:03:39.236443

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4319c7486942'
down_revision: Union[str, None] = '9d85f82c5e03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_delegates',
    sa.Column('delegate_id', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('can_submit_changes', sa.Boolean(), nullable=False),
    sa.Column('can_manage_regional', sa.Boolean(), nullable=False),
    sa.Column('delegated_by_id', sa.Integer(), nullable=False),
    sa.Column('delegated_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('revoked_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['delegated_by_id'], ['users.user_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['model_id'], ['models.model_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['revoked_by_id'], ['users.user_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('delegate_id'),
    sa.UniqueConstraint('model_id', 'user_id', name='uq_model_delegate')
    )
    op.create_index(op.f('ix_model_delegates_model_id'), 'model_delegates', ['model_id'], unique=False)
    op.create_index(op.f('ix_model_delegates_user_id'), 'model_delegates', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_model_delegates_user_id'), table_name='model_delegates')
    op.drop_index(op.f('ix_model_delegates_model_id'), table_name='model_delegates')
    op.drop_table('model_delegates')
    # ### end Alembic commands ###
