"""Add model_change_lead_time_days to validation_policies

Revision ID: 4ed613a27144
Revises: 033fd221e8cf
Create Date: 2025-11-19 16:49:19.150023

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ed613a27144'
down_revision: Union[str, None] = '033fd221e8cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('validation_policies', sa.Column('model_change_lead_time_days', sa.Integer(), nullable=False, server_default='90', comment='Lead time in days before model change implementation date to trigger interim validation'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('validation_policies', 'model_change_lead_time_days')
    # ### end Alembic commands ###
