"""add model_change_lead_time to validation_workflow_slas

Revision ID: 5692dfd2d5e7
Revises: 4d919b53c0cc
Create Date: 2025-11-18 04:53:23.932944

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5692dfd2d5e7'
down_revision: Union[str, None] = '4d919b53c0cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('model_change_categories_code_key', 'model_change_categories', type_='unique')
    op.drop_index('ix_model_change_categories_code', table_name='model_change_categories')
    op.create_index(op.f('ix_model_change_categories_code'), 'model_change_categories', ['code'], unique=True)
    op.drop_constraint('uq_model_version_number', 'model_versions', type_='unique')
    op.add_column('validation_workflow_slas', sa.Column('model_change_lead_time_days', sa.Integer(), nullable=False, server_default='90', comment='Lead time in days before model change implementation date to trigger interim validation'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('validation_workflow_slas', 'model_change_lead_time_days')
    op.create_unique_constraint('uq_model_version_number', 'model_versions', ['model_id', 'version_number'])
    op.drop_index(op.f('ix_model_change_categories_code'), table_name='model_change_categories')
    op.create_index('ix_model_change_categories_code', 'model_change_categories', ['code'], unique=False)
    op.create_unique_constraint('model_change_categories_code_key', 'model_change_categories', ['code'])
    # ### end Alembic commands ###
