"""add validation workflow sla configuration

Revision ID: 6105c56a44ec
Revises: d94bd54f4382
Create Date: 2025-11-17 22:45:22.867668

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6105c56a44ec'
down_revision: Union[str, None] = 'd94bd54f4382'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('validation_workflow_slas',
    sa.Column('sla_id', sa.Integer(), nullable=False),
    sa.Column('workflow_type', sa.String(length=100), nullable=False),
    sa.Column('assignment_days', sa.Integer(), nullable=False),
    sa.Column('begin_work_days', sa.Integer(), nullable=False),
    sa.Column('complete_work_days', sa.Integer(), nullable=False),
    sa.Column('approval_days', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('sla_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('validation_workflow_slas')
    # ### end Alembic commands ###
