"""Add regional override for recommendation priority

Revision ID: 64cb4ff2a1b0
Revises: b18069c182f0
Create Date: 2025-11-30 16:03:24.284903

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64cb4ff2a1b0'
down_revision: Union[str, None] = 'b18069c182f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recommendation_priority_regional_overrides',
    sa.Column('override_id', sa.Integer(), nullable=False),
    sa.Column('priority_id', sa.Integer(), nullable=False, comment='FK to priority taxonomy value (High/Medium/Low/Consideration)'),
    sa.Column('region_id', sa.Integer(), nullable=False, comment='FK to region for this override'),
    sa.Column('requires_action_plan', sa.Boolean(), nullable=True, comment='Override for action plan requirement. NULL = inherit from base config'),
    sa.Column('requires_final_approval', sa.Boolean(), nullable=True, comment='Override for final approval requirement. NULL = inherit from base config'),
    sa.Column('description', sa.Text(), nullable=True, comment='Admin notes explaining why this regional override exists'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['priority_id'], ['taxonomy_values.value_id'], ),
    sa.ForeignKeyConstraint(['region_id'], ['regions.region_id'], ),
    sa.PrimaryKeyConstraint('override_id'),
    sa.UniqueConstraint('priority_id', 'region_id', name='uq_priority_region_override')
    )
    op.alter_column('recommendation_priority_configs', 'priority_id',
               existing_type=sa.INTEGER(),
               comment='FK to priority taxonomy value (High/Medium/Low/Consideration)',
               existing_comment='FK to priority taxonomy value (High/Medium/Low)',
               existing_nullable=False)
    op.alter_column('recommendation_priority_configs', 'requires_action_plan',
               existing_type=sa.BOOLEAN(),
               comment='If false, recommendations with this priority can skip action plan submission',
               existing_nullable=False,
               existing_server_default=sa.text('true'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('recommendation_priority_configs', 'requires_action_plan',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='If false, recommendations with this priority can skip action plan submission',
               existing_nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('recommendation_priority_configs', 'priority_id',
               existing_type=sa.INTEGER(),
               comment='FK to priority taxonomy value (High/Medium/Low)',
               existing_comment='FK to priority taxonomy value (High/Medium/Low/Consideration)',
               existing_nullable=False)
    op.drop_table('recommendation_priority_regional_overrides')
    # ### end Alembic commands ###
