"""create_fry_tables

Revision ID: 6a7ec59943ec
Revises: cb131e53a32a
Create Date: 2025-11-24 18:16:06.091033

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a7ec59943ec'
down_revision: Union[str, None] = 'cb131e53a32a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fry_reports',
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('report_code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('report_id'),
    sa.UniqueConstraint('report_code')
    )
    op.create_table('fry_schedules',
    sa.Column('schedule_id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('schedule_code', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['fry_reports.report_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('schedule_id')
    )
    op.create_index(op.f('ix_fry_schedules_report_id'), 'fry_schedules', ['report_id'], unique=False)
    op.create_table('fry_metric_groups',
    sa.Column('metric_group_id', sa.Integer(), nullable=False),
    sa.Column('schedule_id', sa.Integer(), nullable=False),
    sa.Column('metric_group_name', sa.String(length=200), nullable=False),
    sa.Column('model_driven', sa.Boolean(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['schedule_id'], ['fry_schedules.schedule_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('metric_group_id')
    )
    op.create_index(op.f('ix_fry_metric_groups_schedule_id'), 'fry_metric_groups', ['schedule_id'], unique=False)
    op.create_table('fry_line_items',
    sa.Column('line_item_id', sa.Integer(), nullable=False),
    sa.Column('metric_group_id', sa.Integer(), nullable=False),
    sa.Column('line_item_text', sa.Text(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['metric_group_id'], ['fry_metric_groups.metric_group_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('line_item_id')
    )
    op.create_index(op.f('ix_fry_line_items_metric_group_id'), 'fry_line_items', ['metric_group_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fry_line_items_metric_group_id'), table_name='fry_line_items')
    op.drop_table('fry_line_items')
    op.drop_index(op.f('ix_fry_metric_groups_schedule_id'), table_name='fry_metric_groups')
    op.drop_table('fry_metric_groups')
    op.drop_index(op.f('ix_fry_schedules_report_id'), table_name='fry_schedules')
    op.drop_table('fry_schedules')
    op.drop_table('fry_reports')
    # ### end Alembic commands ###
