"""add_model_type_taxonomy

Revision ID: 7466212450b8
Revises: fda5832f9922
Create Date: 2025-11-23 23:43:42.429902

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7466212450b8'
down_revision: Union[str, None] = 'fda5832f9922'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_type_categories',
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('category_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('model_types',
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['model_type_categories.category_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('type_id')
    )
    op.create_index(op.f('ix_model_types_category_id'), 'model_types', ['category_id'], unique=False)
    op.drop_constraint('uq_model_hierarchy_child_model_id', 'model_hierarchy', type_='unique')
    op.drop_constraint('models_model_type_id_fkey', 'models', type_='foreignkey')
    op.create_foreign_key(None, 'models', 'model_types', ['model_type_id'], ['type_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'models', type_='foreignkey')
    op.create_foreign_key('models_model_type_id_fkey', 'models', 'taxonomy_values', ['model_type_id'], ['value_id'])
    op.create_unique_constraint('uq_model_hierarchy_child_model_id', 'model_hierarchy', ['child_model_id'])
    op.drop_index(op.f('ix_model_types_category_id'), table_name='model_types')
    op.drop_table('model_types')
    op.drop_table('model_type_categories')
    # ### end Alembic commands ###
