"""add_validations_table

Revision ID: 84c4a05e710d
Revises: g8h69i1d2345
Create Date: 2025-11-17 13:54:08.305357

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84c4a05e710d'
down_revision: Union[str, None] = 'g8h69i1d2345'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('validation_policies',
    sa.Column('policy_id', sa.Integer(), nullable=False),
    sa.Column('risk_tier_id', sa.Integer(), nullable=False),
    sa.Column('frequency_months', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['risk_tier_id'], ['taxonomy_values.value_id'], ),
    sa.PrimaryKeyConstraint('policy_id'),
    sa.UniqueConstraint('risk_tier_id')
    )
    op.create_table('validations',
    sa.Column('validation_id', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.Column('validation_date', sa.Date(), nullable=False),
    sa.Column('validator_id', sa.Integer(), nullable=False),
    sa.Column('validation_type_id', sa.Integer(), nullable=False),
    sa.Column('outcome_id', sa.Integer(), nullable=False),
    sa.Column('scope_id', sa.Integer(), nullable=False),
    sa.Column('findings_summary', sa.Text(), nullable=True),
    sa.Column('report_reference', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['models.model_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['outcome_id'], ['taxonomy_values.value_id'], ),
    sa.ForeignKeyConstraint(['scope_id'], ['taxonomy_values.value_id'], ),
    sa.ForeignKeyConstraint(['validation_type_id'], ['taxonomy_values.value_id'], ),
    sa.ForeignKeyConstraint(['validator_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('validation_id')
    )
    op.drop_index('ix_audit_logs_entity', table_name='audit_logs')
    op.alter_column('taxonomy_values', 'sort_order',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('taxonomy_values', 'sort_order',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index('ix_audit_logs_entity', 'audit_logs', ['entity_type', 'entity_id'], unique=False)
    op.drop_table('validations')
    op.drop_table('validation_policies')
    # ### end Alembic commands ###
