"""add_monitoring_cycle_id_to_recommendations

Revision ID: a07058b071de
Revises: 3d0a564c4fe3
Create Date: 2025-11-30 13:23:02.410556

"""
from typing import Sequence, Union, cast
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a07058b071de'
down_revision: Union[str, None] = '3d0a564c4fe3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recommendations', sa.Column('monitoring_cycle_id', sa.Integer(), nullable=True, comment='Link to originating monitoring cycle (if applicable)'))
    op.create_index(op.f('ix_recommendations_monitoring_cycle_id'), 'recommendations', ['monitoring_cycle_id'], unique=False)
    op.create_foreign_key(None, 'recommendations', 'monitoring_cycles', ['monitoring_cycle_id'], ['cycle_id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(cast(str, None), 'recommendations', type_='foreignkey')
    op.drop_index(op.f('ix_recommendations_monitoring_cycle_id'), table_name='recommendations')
    op.drop_column('recommendations', 'monitoring_cycle_id')
    # ### end Alembic commands ###
