"""add model submission approval workflow

Revision ID: bb4e0262b97a
Revises: d8342786dfaa
Create Date: 2025-11-21 13:53:47.882625

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb4e0262b97a'
down_revision: Union[str, None] = 'd8342786dfaa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Add row_approval_status and submission tracking to models table
    op.add_column('models', sa.Column('row_approval_status', sa.String(20), nullable=True,
                                      comment='Status of this record in the approval workflow: pending, needs_revision, rejected, or NULL (approved)'))
    op.add_column('models', sa.Column('submitted_by_user_id', sa.Integer(), nullable=True,
                                      comment='User who submitted this model for approval'))
    op.add_column('models', sa.Column('submitted_at', sa.TIMESTAMP(), nullable=True,
                                      comment='Timestamp when model was first submitted'))

    # Add foreign key for submitted_by_user_id
    op.create_foreign_key('fk_models_submitted_by_user', 'models', 'users',
                          ['submitted_by_user_id'], ['user_id'], ondelete='SET NULL')

    # Create model_submission_comments table for iterative review conversation
    op.create_table('model_submission_comments',
        sa.Column('comment_id', sa.Integer(), nullable=False),
        sa.Column('model_id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('comment_text', sa.Text(), nullable=False),
        sa.Column('action_taken', sa.String(50), nullable=True,
                  comment='Action: submitted, sent_back, resubmitted, approved, rejected'),
        sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('NOW()'), nullable=False),
        sa.PrimaryKeyConstraint('comment_id'),
        sa.ForeignKeyConstraint(['model_id'], ['models.model_id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE')
    )

    # Create index for faster lookups
    op.create_index('ix_model_submission_comments_model_id', 'model_submission_comments', ['model_id'])

    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('validation_requests', 'prior_validation_request_id',
               existing_type=sa.INTEGER(),
               comment='Link to the previous validation that this revalidation follows',
               existing_nullable=True)
    op.alter_column('validation_requests', 'submission_received_date',
               existing_type=sa.DATE(),
               comment='Date model owner actually submitted documentation',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # Drop model submission comments table
    op.drop_index('ix_model_submission_comments_model_id', table_name='model_submission_comments')
    op.drop_table('model_submission_comments')

    # Drop columns from models table
    op.drop_constraint('fk_models_submitted_by_user', 'models', type_='foreignkey')
    op.drop_column('models', 'submitted_at')
    op.drop_column('models', 'submitted_by_user_id')
    op.drop_column('models', 'row_approval_status')

    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('validation_requests', 'submission_received_date',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='Date model owner actually submitted documentation',
               existing_nullable=True)
    op.alter_column('validation_requests', 'prior_validation_request_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Link to the previous validation that this revalidation follows',
               existing_nullable=True)
    # ### end Alembic commands ###
