"""add_validation_grouping_memory

Revision ID: c1f27142d859
Revises: 13f967c5714a
Create Date: 2025-11-19 13:50:21.773450

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1f27142d859'
down_revision: Union[str, None] = '13f967c5714a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('validation_grouping_memory',
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.Column('last_validation_request_id', sa.Integer(), nullable=False),
    sa.Column('grouped_model_ids', sa.Text(), nullable=False),
    sa.Column('is_regular_validation', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['last_validation_request_id'], ['validation_requests.request_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['model_id'], ['models.model_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('model_id')
    )
    op.create_index(op.f('ix_validation_grouping_memory_last_validation_request_id'), 'validation_grouping_memory', ['last_validation_request_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_validation_grouping_memory_last_validation_request_id'), table_name='validation_grouping_memory')
    op.drop_table('validation_grouping_memory')
    # ### end Alembic commands ###
