"""add_fry_14_reporting_schema

Revision ID: cb131e53a32a
Revises: f4f4f0d7f445
Create Date: 2025-11-24 18:11:28.381747

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb131e53a32a'
down_revision: Union[str, None] = 'f4f4f0d7f445'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_conditional_rules_is_active', table_name='conditional_approval_rules')
    op.create_index(op.f('ix_conditional_approval_rules_is_active'), 'conditional_approval_rules', ['is_active'], unique=False)
    op.drop_index('ix_rule_required_approvers_role', table_name='rule_required_approvers')
    op.drop_index('ix_rule_required_approvers_rule', table_name='rule_required_approvers')
    op.create_index(op.f('ix_rule_required_approvers_approver_role_id'), 'rule_required_approvers', ['approver_role_id'], unique=False)
    op.create_index(op.f('ix_rule_required_approvers_rule_id'), 'rule_required_approvers', ['rule_id'], unique=False)
    op.drop_index('ix_validation_approvals_approver_role', table_name='validation_approvals')
    op.create_index(op.f('ix_validation_approvals_approver_role_id'), 'validation_approvals', ['approver_role_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_validation_approvals_approver_role_id'), table_name='validation_approvals')
    op.create_index('ix_validation_approvals_approver_role', 'validation_approvals', ['approver_role_id'], unique=False)
    op.drop_index(op.f('ix_rule_required_approvers_rule_id'), table_name='rule_required_approvers')
    op.drop_index(op.f('ix_rule_required_approvers_approver_role_id'), table_name='rule_required_approvers')
    op.create_index('ix_rule_required_approvers_rule', 'rule_required_approvers', ['rule_id'], unique=False)
    op.create_index('ix_rule_required_approvers_role', 'rule_required_approvers', ['approver_role_id'], unique=False)
    op.drop_index(op.f('ix_conditional_approval_rules_is_active'), table_name='conditional_approval_rules')
    op.create_index('ix_conditional_rules_is_active', 'conditional_approval_rules', ['is_active'], unique=False)
    # ### end Alembic commands ###
