"""Add validation plan tables

Revision ID: cc568f455fb3
Revises: 69f9c73f2d63
Create Date: 2025-11-22 14:49:24.648514

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cc568f455fb3'
down_revision: Union[str, None] = '69f9c73f2d63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('validation_component_definitions',
    sa.Column('component_id', sa.Integer(), nullable=False),
    sa.Column('section_number', sa.String(length=10), nullable=False),
    sa.Column('section_title', sa.String(length=200), nullable=False),
    sa.Column('component_code', sa.String(length=20), nullable=False, comment="Stable identifier like '1.1', '3.4'"),
    sa.Column('component_title', sa.String(length=200), nullable=False),
    sa.Column('is_test_or_analysis', sa.Boolean(), nullable=False, comment='True if test/analysis, False if report section'),
    sa.Column('expectation_high', sa.String(length=20), nullable=False),
    sa.Column('expectation_medium', sa.String(length=20), nullable=False),
    sa.Column('expectation_low', sa.String(length=20), nullable=False),
    sa.Column('expectation_very_low', sa.String(length=20), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('component_id'),
    sa.UniqueConstraint('component_code')
    )
    op.create_table('validation_plans',
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('overall_scope_summary', sa.Text(), nullable=True),
    sa.Column('material_deviation_from_standard', sa.Boolean(), nullable=False),
    sa.Column('overall_deviation_rationale', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['validation_requests.request_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('plan_id'),
    sa.UniqueConstraint('request_id')
    )
    op.create_table('validation_plan_components',
    sa.Column('plan_component_id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('component_id', sa.Integer(), nullable=False),
    sa.Column('default_expectation', sa.String(length=20), nullable=False, comment='Required, IfApplicable, or NotExpected'),
    sa.Column('planned_treatment', sa.String(length=20), nullable=False, comment='Planned, NotPlanned, or NotApplicable'),
    sa.Column('is_deviation', sa.Boolean(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('additional_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['component_id'], ['validation_component_definitions.component_id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['validation_plans.plan_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('plan_component_id')
    )
    # Use raw SQL with IF EXISTS to handle fresh databases where these tables may not exist
    op.execute('DROP INDEX IF EXISTS ix_validations_region_id')
    op.execute('DROP TABLE IF EXISTS validations')
    op.execute('DROP INDEX IF EXISTS ix_version_deployment_tasks_assigned_to_id')
    op.execute('DROP INDEX IF EXISTS ix_version_deployment_tasks_planned_date')
    op.execute('DROP INDEX IF EXISTS ix_version_deployment_tasks_status')
    op.execute('DROP TABLE IF EXISTS version_deployment_tasks')
    op.execute('DROP TABLE IF EXISTS saved_queries')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('saved_queries',
    sa.Column('query_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('query_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('query_text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_public', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name='saved_queries_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('query_id', name='saved_queries_pkey')
    )
    op.create_table('version_deployment_tasks',
    sa.Column('task_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('version_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('model_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('region_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('planned_production_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('actual_production_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('assigned_to_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'PENDING'::character varying"), autoincrement=False, nullable=False),
    sa.Column('confirmation_notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('confirmed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('confirmed_by_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('deployed_before_validation_approved', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('validation_override_reason', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['users.user_id'], name='fk_version_deployment_tasks_assigned_to_id'),
    sa.ForeignKeyConstraint(['confirmed_by_id'], ['users.user_id'], name='fk_version_deployment_tasks_confirmed_by_id'),
    sa.ForeignKeyConstraint(['model_id'], ['models.model_id'], name='fk_version_deployment_tasks_model_id', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['region_id'], ['regions.region_id'], name='fk_version_deployment_tasks_region_id', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['version_id'], ['model_versions.version_id'], name='fk_version_deployment_tasks_version_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('task_id', name='version_deployment_tasks_pkey')
    )
    op.create_index('ix_version_deployment_tasks_status', 'version_deployment_tasks', ['status'], unique=False)
    op.create_index('ix_version_deployment_tasks_planned_date', 'version_deployment_tasks', ['planned_production_date'], unique=False)
    op.create_index('ix_version_deployment_tasks_assigned_to_id', 'version_deployment_tasks', ['assigned_to_id'], unique=False)
    op.create_table('validations',
    sa.Column('validation_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('model_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('validation_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('validator_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('validation_type_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('outcome_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('scope_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('findings_summary', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('report_reference', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('region_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['model_id'], ['models.model_id'], name='validations_model_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['outcome_id'], ['taxonomy_values.value_id'], name='validations_outcome_id_fkey'),
    sa.ForeignKeyConstraint(['region_id'], ['regions.region_id'], name='fk_validations_region', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['scope_id'], ['taxonomy_values.value_id'], name='validations_scope_id_fkey'),
    sa.ForeignKeyConstraint(['validation_type_id'], ['taxonomy_values.value_id'], name='validations_validation_type_id_fkey'),
    sa.ForeignKeyConstraint(['validator_id'], ['users.user_id'], name='validations_validator_id_fkey'),
    sa.PrimaryKeyConstraint('validation_id', name='validations_pkey')
    )
    op.create_index('ix_validations_region_id', 'validations', ['region_id'], unique=False)
    op.drop_table('validation_plan_components')
    op.drop_table('validation_plans')
    op.drop_table('validation_component_definitions')
    # ### end Alembic commands ###
