"""add_is_model_boolean_to_models

Revision ID: cc7c2819a59c
Revises: 7b23f448cd80
Create Date: 2025-11-25 04:16:41.040603

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc7c2819a59c'
down_revision: Union[str, None] = '7b23f448cd80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Add column with server default to handle existing rows
    op.add_column('models', sa.Column('is_model', sa.Boolean(), nullable=False, server_default='true', comment='True for actual models, False for non-model tools/applications'))
    # Remove the server default after existing rows are populated
    op.alter_column('models', 'is_model', server_default=None)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('models', 'is_model')
    # ### end Alembic commands ###
