"""update_model_regions_remove_risk_level_add_version

Revision ID: d6989a9d64c9
Revises: 4319c7486942
Create Date: 2025-11-18 02:08:00.942047

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6989a9d64c9'
down_revision: Union[str, None] = '4319c7486942'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('model_regions', sa.Column('version_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'model_regions', 'model_versions', ['version_id'], ['version_id'], ondelete='SET NULL')
    op.drop_column('model_regions', 'regional_risk_level')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('model_regions', sa.Column('regional_risk_level', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'model_regions', type_='foreignkey')
    op.drop_column('model_regions', 'version_id')
    # ### end Alembic commands ###
