"""add_reviewer_role_to_assignments

Revision ID: d94bd54f4382
Revises: h9i70j2e3456
Create Date: 2025-11-17 21:18:22.914063

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd94bd54f4382'
down_revision: Union[str, None] = 'h9i70j2e3456'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('validation_assignments', sa.Column('is_reviewer', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('validation_assignments', sa.Column('reviewer_signed_off', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('validation_assignments', sa.Column('reviewer_signed_off_at', sa.DateTime(), nullable=True))
    op.add_column('validation_assignments', sa.Column('reviewer_sign_off_comments', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('validation_assignments', 'reviewer_sign_off_comments')
    op.drop_column('validation_assignments', 'reviewer_signed_off_at')
    op.drop_column('validation_assignments', 'reviewer_signed_off')
    op.drop_column('validation_assignments', 'is_reviewer')
    # ### end Alembic commands ###
