"""add version deployment tasks table

Revision ID: df64c68f39b8
Revises: 373700cdc73d
Create Date: 2025-11-23 00:31:13.011208

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df64c68f39b8'
down_revision: Union[str, None] = '373700cdc73d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('version_deployment_tasks',
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.Column('region_id', sa.Integer(), nullable=True, comment='NULL for global deployment'),
    sa.Column('planned_production_date', sa.Date(), nullable=False),
    sa.Column('actual_production_date', sa.Date(), nullable=True),
    sa.Column('assigned_to_id', sa.Integer(), nullable=False, comment='Model Owner or delegate'),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('confirmation_notes', sa.Text(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('confirmed_by_id', sa.Integer(), nullable=True),
    sa.Column('deployed_before_validation_approved', sa.Boolean(), nullable=False, comment='True if deployed before validation was approved'),
    sa.Column('validation_override_reason', sa.Text(), nullable=True, comment='Justification for deploying before validation approval'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['confirmed_by_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['model_id'], ['models.model_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['region_id'], ['regions.region_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['version_id'], ['model_versions.version_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('task_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('version_deployment_tasks')
    # ### end Alembic commands ###
