"""Add requires_regional_approval to regions

Revision ID: f1cc30cb20bf
Revises: c1f27142d859
Create Date: 2025-11-19 14:08:04.782504

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1cc30cb20bf'
down_revision: Union[str, None] = 'c1f27142d859'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('regions', sa.Column('requires_regional_approval', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('regions', 'requires_regional_approval')
    # ### end Alembic commands ###
